;;;; conditions.lisp — Condition hierarchy and error code map for Senzing
;;;
;;; Copyright (C) 2024-2026 Senzing, Inc. All Rights Reserved.
;;; Licensed under the Apache License, Version 2.0
;;;
;;; Mirrors the Python hierarchy from szerror.py exactly.

(in-package #:sz-sdk.conditions)

;;; ---------------------------------------------------------------------------
;;; Base condition
;;; ---------------------------------------------------------------------------

(define-condition sz-error (error)
  ((error-code
    :initarg :error-code
    :initform 0
    :reader sz-error-code)
   (error-message
    :initarg :error-message
    :initform ""
    :reader sz-error-message))
  (:report (lambda (condition stream)
             (format stream "SzError ~D: ~A"
                     (sz-error-code condition)
                     (sz-error-message condition)))))

;;; ---------------------------------------------------------------------------
;;; Condition-defining macro
;;; ---------------------------------------------------------------------------

(defmacro define-sz-condition (name parent report-prefix)
  "Define a Senzing condition with a standard report format.
   Expands to DEFINE-CONDITION with a :REPORT that prints
   \"<REPORT-PREFIX> <code>: <message>\"."
  `(define-condition ,name (,parent) ()
     (:report (lambda (c s)
                (format s ,(format nil "~A ~~D: ~~A" report-prefix)
                        (sz-error-code c) (sz-error-message c))))))

;;; ---------------------------------------------------------------------------
;;; Category conditions
;;; ---------------------------------------------------------------------------

(define-sz-condition sz-bad-input-error       sz-error "SzBadInputError")
(define-sz-condition sz-general-error         sz-error "SzGeneralError")
(define-sz-condition sz-retryable-error       sz-error "SzRetryableError")
(define-sz-condition sz-unrecoverable-error   sz-error "SzUnrecoverableError")

;;; ---------------------------------------------------------------------------
;;; Detail conditions — bad input
;;; ---------------------------------------------------------------------------

(define-sz-condition sz-not-found-error             sz-bad-input-error "SzNotFoundError")
(define-sz-condition sz-unknown-data-source-error   sz-bad-input-error "SzUnknownDataSourceError")

;;; ---------------------------------------------------------------------------
;;; Detail conditions — general
;;; ---------------------------------------------------------------------------

(define-sz-condition sz-configuration-error     sz-general-error "SzConfigurationError")
(define-sz-condition sz-replace-conflict-error  sz-general-error "SzReplaceConflictError")
(define-sz-condition sz-sdk-error               sz-general-error "SzSdkError")

;;; ---------------------------------------------------------------------------
;;; Detail conditions — retryable
;;; ---------------------------------------------------------------------------

(define-sz-condition sz-database-connection-lost-error  sz-retryable-error "SzDatabaseConnectionLostError")
(define-sz-condition sz-database-transient-error        sz-retryable-error "SzDatabaseTransientError")
(define-sz-condition sz-retry-timeout-exceeded-error    sz-retryable-error "SzRetryTimeoutExceededError")

;;; ---------------------------------------------------------------------------
;;; Detail conditions — unrecoverable
;;; ---------------------------------------------------------------------------

(define-sz-condition sz-database-error          sz-unrecoverable-error "SzDatabaseError")
(define-sz-condition sz-license-error           sz-unrecoverable-error "SzLicenseError")
(define-sz-condition sz-not-initialized-error   sz-unrecoverable-error "SzNotInitializedError")
(define-sz-condition sz-unhandled-error         sz-unrecoverable-error "SzUnhandledError")

;;; ---------------------------------------------------------------------------
;;; Engine exception map — maps error codes to condition classes
;;; Generated from sz-sdk-python/src/senzing/szerror.py ENGINE_EXCEPTION_MAP
;;; ---------------------------------------------------------------------------

(defvar *engine-exception-map*
  (let ((ht (make-hash-table :test #'eql)))
    (flet ((m (code class)
             (setf (gethash code ht) class)))
      (m 2 'sz-bad-input-error)
      (m 5 'sz-error)
      (m 7 'sz-bad-input-error)
      (m 10 'sz-retry-timeout-exceeded-error)
      (m 14 'sz-configuration-error)
      (m 18 'sz-error)
      (m 19 'sz-configuration-error)
      (m 20 'sz-configuration-error)
      (m 21 'sz-configuration-error)
      (m 22 'sz-bad-input-error)
      (m 23 'sz-bad-input-error)
      (m 24 'sz-bad-input-error)
      (m 25 'sz-bad-input-error)
      (m 26 'sz-bad-input-error)
      (m 27 'sz-error)
      (m 28 'sz-configuration-error)
      (m 29 'sz-error)
      (m 30 'sz-configuration-error)
      (m 31 'sz-error)
      (m 32 'sz-error)
      (m 33 'sz-not-found-error)
      (m 34 'sz-configuration-error)
      (m 35 'sz-configuration-error)
      (m 36 'sz-configuration-error)
      (m 37 'sz-not-found-error)
      (m 38 'sz-error)
      (m 39 'sz-error)
      (m 40 'sz-configuration-error)
      (m 41 'sz-error)
      (m 42 'sz-error)
      (m 43 'sz-error)
      (m 45 'sz-error)
      (m 46 'sz-error)
      (m 47 'sz-error)
      (m 48 'sz-not-initialized-error)
      (m 49 'sz-not-initialized-error)
      (m 50 'sz-not-initialized-error)
      (m 51 'sz-bad-input-error)
      (m 52 'sz-error)
      (m 53 'sz-not-initialized-error)
      (m 54 'sz-database-error)
      (m 55 'sz-error)
      (m 56 'sz-error)
      (m 57 'sz-error)
      (m 58 'sz-error)
      (m 60 'sz-configuration-error)
      (m 61 'sz-configuration-error)
      (m 62 'sz-configuration-error)
      (m 64 'sz-configuration-error)
      (m 65 'sz-bad-input-error)
      (m 66 'sz-bad-input-error)
      (m 67 'sz-configuration-error)
      (m 68 'sz-error)
      (m 69 'sz-error)
      (m 76 'sz-error)
      (m 77 'sz-error)
      (m 78 'sz-error)
      (m 79 'sz-error)
      (m 80 'sz-error)
      (m 81 'sz-error)
      (m 82 'sz-error)
      (m 83 'sz-error)
      (m 84 'sz-error)
      (m 85 'sz-error)
      (m 86 'sz-error)
      (m 87 'sz-unhandled-error)
      (m 88 'sz-bad-input-error)
      (m 89 'sz-configuration-error)
      (m 90 'sz-configuration-error)
      (m 91 'sz-error)
      (m 92 'sz-error)
      (m 93 'sz-error)
      (m 94 'sz-error)
      (m 95 'sz-error)
      (m 96 'sz-error)
      (m 97 'sz-error)
      (m 98 'sz-error)
      (m 999 'sz-license-error)
      (m 1000 'sz-database-error)
      (m 1001 'sz-database-error)
      (m 1002 'sz-database-error)
      (m 1003 'sz-database-error)
      (m 1004 'sz-database-error)
      (m 1005 'sz-database-error)
      (m 1006 'sz-database-connection-lost-error)
      (m 1007 'sz-database-connection-lost-error)
      (m 1008 'sz-database-transient-error)
      (m 1009 'sz-database-error)
      (m 1010 'sz-database-error)
      (m 1011 'sz-database-error)
      (m 1012 'sz-database-error)
      (m 1013 'sz-database-error)
      (m 1014 'sz-database-error)
      (m 1015 'sz-database-error)
      (m 1016 'sz-database-error)
      (m 1017 'sz-database-error)
      (m 1018 'sz-database-error)
      (m 1019 'sz-configuration-error)
      (m 2001 'sz-configuration-error)
      (m 2002 'sz-error)
      (m 2003 'sz-error)
      (m 2005 'sz-error)
      (m 2006 'sz-error)
      (m 2007 'sz-error)
      (m 2009 'sz-error)
      (m 2010 'sz-error)
      (m 2012 'sz-configuration-error)
      (m 2015 'sz-configuration-error)
      (m 2027 'sz-error)
      (m 2029 'sz-configuration-error)
      (m 2034 'sz-configuration-error)
      (m 2036 'sz-configuration-error)
      (m 2037 'sz-configuration-error)
      (m 2038 'sz-configuration-error)
      (m 2041 'sz-configuration-error)
      (m 2045 'sz-configuration-error)
      (m 2047 'sz-configuration-error)
      (m 2048 'sz-configuration-error)
      (m 2049 'sz-configuration-error)
      (m 2050 'sz-configuration-error)
      (m 2051 'sz-configuration-error)
      (m 2057 'sz-bad-input-error)
      (m 2061 'sz-configuration-error)
      (m 2062 'sz-configuration-error)
      (m 2065 'sz-configuration-error)
      (m 2066 'sz-configuration-error)
      (m 2067 'sz-configuration-error)
      (m 2069 'sz-configuration-error)
      (m 2070 'sz-configuration-error)
      (m 2071 'sz-configuration-error)
      (m 2073 'sz-error)
      (m 2074 'sz-error)
      (m 2075 'sz-configuration-error)
      (m 2076 'sz-configuration-error)
      (m 2079 'sz-configuration-error)
      (m 2080 'sz-configuration-error)
      (m 2081 'sz-configuration-error)
      (m 2082 'sz-configuration-error)
      (m 2083 'sz-configuration-error)
      (m 2084 'sz-configuration-error)
      (m 2088 'sz-configuration-error)
      (m 2089 'sz-configuration-error)
      (m 2090 'sz-configuration-error)
      (m 2091 'sz-configuration-error)
      (m 2092 'sz-configuration-error)
      (m 2093 'sz-configuration-error)
      (m 2094 'sz-configuration-error)
      (m 2095 'sz-configuration-error)
      (m 2097 'sz-error)
      (m 2099 'sz-configuration-error)
      (m 2101 'sz-configuration-error)
      (m 2102 'sz-configuration-error)
      (m 2103 'sz-configuration-error)
      (m 2104 'sz-configuration-error)
      (m 2105 'sz-configuration-error)
      (m 2106 'sz-configuration-error)
      (m 2107 'sz-configuration-error)
      (m 2108 'sz-configuration-error)
      (m 2109 'sz-configuration-error)
      (m 2110 'sz-configuration-error)
      (m 2111 'sz-configuration-error)
      (m 2112 'sz-configuration-error)
      (m 2113 'sz-configuration-error)
      (m 2114 'sz-configuration-error)
      (m 2116 'sz-error)
      (m 2117 'sz-configuration-error)
      (m 2118 'sz-configuration-error)
      (m 2120 'sz-configuration-error)
      (m 2121 'sz-configuration-error)
      (m 2123 'sz-configuration-error)
      (m 2124 'sz-error)
      (m 2131 'sz-configuration-error)
      (m 2135 'sz-configuration-error)
      (m 2136 'sz-configuration-error)
      (m 2137 'sz-configuration-error)
      (m 2138 'sz-configuration-error)
      (m 2139 'sz-configuration-error)
      (m 2205 'sz-configuration-error)
      (m 2206 'sz-configuration-error)
      (m 2207 'sz-unknown-data-source-error)
      (m 2209 'sz-configuration-error)
      (m 2210 'sz-configuration-error)
      (m 2211 'sz-configuration-error)
      (m 2212 'sz-configuration-error)
      (m 2213 'sz-configuration-error)
      (m 2214 'sz-configuration-error)
      (m 2215 'sz-configuration-error)
      (m 2216 'sz-configuration-error)
      (m 2217 'sz-configuration-error)
      (m 2218 'sz-configuration-error)
      (m 2219 'sz-configuration-error)
      (m 2220 'sz-configuration-error)
      (m 2221 'sz-configuration-error)
      (m 2222 'sz-configuration-error)
      (m 2223 'sz-configuration-error)
      (m 2224 'sz-configuration-error)
      (m 2225 'sz-configuration-error)
      (m 2226 'sz-configuration-error)
      (m 2227 'sz-configuration-error)
      (m 2228 'sz-configuration-error)
      (m 2230 'sz-configuration-error)
      (m 2231 'sz-configuration-error)
      (m 2232 'sz-configuration-error)
      (m 2233 'sz-configuration-error)
      (m 2234 'sz-configuration-error)
      (m 2235 'sz-configuration-error)
      (m 2236 'sz-configuration-error)
      (m 2237 'sz-configuration-error)
      (m 2238 'sz-configuration-error)
      (m 2239 'sz-configuration-error)
      (m 2240 'sz-configuration-error)
      (m 2241 'sz-configuration-error)
      (m 2242 'sz-configuration-error)
      (m 2243 'sz-configuration-error)
      (m 2244 'sz-configuration-error)
      (m 2245 'sz-configuration-error)
      (m 2246 'sz-configuration-error)
      (m 2247 'sz-configuration-error)
      (m 2248 'sz-configuration-error)
      (m 2249 'sz-configuration-error)
      (m 2250 'sz-configuration-error)
      (m 2251 'sz-configuration-error)
      (m 2252 'sz-configuration-error)
      (m 2253 'sz-configuration-error)
      (m 2254 'sz-configuration-error)
      (m 2255 'sz-configuration-error)
      (m 2256 'sz-configuration-error)
      (m 2257 'sz-configuration-error)
      (m 2258 'sz-configuration-error)
      (m 2259 'sz-configuration-error)
      (m 2260 'sz-configuration-error)
      (m 2261 'sz-configuration-error)
      (m 2262 'sz-configuration-error)
      (m 2263 'sz-configuration-error)
      (m 2264 'sz-configuration-error)
      (m 2266 'sz-configuration-error)
      (m 2267 'sz-configuration-error)
      (m 2268 'sz-configuration-error)
      (m 2269 'sz-configuration-error)
      (m 2270 'sz-configuration-error)
      (m 2271 'sz-configuration-error)
      (m 2272 'sz-configuration-error)
      (m 2273 'sz-configuration-error)
      (m 2274 'sz-configuration-error)
      (m 2275 'sz-configuration-error)
      (m 2276 'sz-configuration-error)
      (m 2277 'sz-configuration-error)
      (m 2278 'sz-configuration-error)
      (m 2279 'sz-configuration-error)
      (m 2280 'sz-configuration-error)
      (m 2281 'sz-configuration-error)
      (m 2282 'sz-configuration-error)
      (m 2283 'sz-configuration-error)
      (m 2285 'sz-error)
      (m 2286 'sz-error)
      (m 2287 'sz-error)
      (m 2288 'sz-error)
      (m 2289 'sz-configuration-error)
      (m 2290 'sz-configuration-error)
      (m 2291 'sz-configuration-error)
      (m 2292 'sz-error)
      (m 2293 'sz-error)
      (m 2294 'sz-error)
      (m 3011 'sz-error)
      (m 3101 'sz-error)
      (m 3102 'sz-error)
      (m 3103 'sz-error)
      (m 3104 'sz-error)
      (m 3110 'sz-error)
      (m 3111 'sz-error)
      (m 3112 'sz-error)
      (m 3121 'sz-bad-input-error)
      (m 3122 'sz-bad-input-error)
      (m 3123 'sz-bad-input-error)
      (m 3124 'sz-error)
      (m 3125 'sz-error)
      (m 3131 'sz-bad-input-error)
      (m 7209 'sz-configuration-error)
      (m 7211 'sz-configuration-error)
      (m 7212 'sz-configuration-error)
      (m 7216 'sz-configuration-error)
      (m 7217 'sz-configuration-error)
      (m 7218 'sz-configuration-error)
      (m 7219 'sz-error)
      (m 7220 'sz-configuration-error)
      (m 7221 'sz-configuration-error)
      (m 7222 'sz-error)
      (m 7223 'sz-configuration-error)
      (m 7224 'sz-configuration-error)
      (m 7226 'sz-configuration-error)
      (m 7227 'sz-configuration-error)
      (m 7228 'sz-configuration-error)
      (m 7230 'sz-configuration-error)
      (m 7232 'sz-configuration-error)
      (m 7233 'sz-configuration-error)
      (m 7234 'sz-configuration-error)
      (m 7235 'sz-configuration-error)
      (m 7236 'sz-configuration-error)
      (m 7237 'sz-configuration-error)
      (m 7238 'sz-error)
      (m 7239 'sz-configuration-error)
      (m 7240 'sz-configuration-error)
      (m 7241 'sz-configuration-error)
      (m 7242 'sz-configuration-error)
      (m 7243 'sz-configuration-error)
      (m 7244 'sz-configuration-error)
      (m 7245 'sz-replace-conflict-error)
      (m 7246 'sz-configuration-error)
      (m 7247 'sz-configuration-error)
      (m 7303 'sz-bad-input-error)
      (m 7305 'sz-bad-input-error)
      (m 7313 'sz-bad-input-error)
      (m 7314 'sz-bad-input-error)
      (m 7317 'sz-configuration-error)
      (m 7344 'sz-configuration-error)
      (m 7426 'sz-bad-input-error)
      (m 7511 'sz-error)
      (m 8000 'sz-bad-input-error)
      (m 8410 'sz-error)
      (m 8501 'sz-configuration-error)
      (m 8502 'sz-error)
      (m 8503 'sz-error)
      (m 8504 'sz-error)
      (m 8505 'sz-error)
      (m 8508 'sz-error)
      (m 8509 'sz-error)
      (m 8514 'sz-error)
      (m 8516 'sz-configuration-error)
      (m 8517 'sz-configuration-error)
      (m 8520 'sz-error)
      (m 8521 'sz-error)
      (m 8522 'sz-configuration-error)
      (m 8524 'sz-error)
      (m 8525 'sz-configuration-error)
      (m 8526 'sz-configuration-error)
      (m 8527 'sz-configuration-error)
      (m 8528 'sz-configuration-error)
      (m 8529 'sz-configuration-error)
      (m 8530 'sz-error)
      (m 8536 'sz-configuration-error)
      (m 8538 'sz-configuration-error)
      (m 8539 'sz-error)
      (m 8540 'sz-configuration-error)
      (m 8541 'sz-error)
      (m 8542 'sz-error)
      (m 8543 'sz-configuration-error)
      (m 8544 'sz-configuration-error)
      (m 8545 'sz-configuration-error)
      (m 8556 'sz-configuration-error)
      (m 8557 'sz-configuration-error)
      (m 8593 'sz-error)
      (m 8594 'sz-error)
      (m 8595 'sz-error)
      (m 8598 'sz-error)
      (m 8599 'sz-configuration-error)
      (m 8601 'sz-configuration-error)
      (m 8602 'sz-configuration-error)
      (m 8603 'sz-error)
      (m 8604 'sz-configuration-error)
      (m 8605 'sz-configuration-error)
      (m 8606 'sz-configuration-error)
      (m 8607 'sz-configuration-error)
      (m 8608 'sz-configuration-error)
      (m 8701 'sz-configuration-error)
      (m 8702 'sz-configuration-error)
      (m 9000 'sz-license-error)
      (m 9107 'sz-configuration-error)
      (m 9110 'sz-configuration-error)
      (m 9111 'sz-configuration-error)
      (m 9112 'sz-configuration-error)
      (m 9113 'sz-configuration-error)
      (m 9115 'sz-bad-input-error)
      (m 9116 'sz-configuration-error)
      (m 9117 'sz-configuration-error)
      (m 9118 'sz-configuration-error)
      (m 9119 'sz-configuration-error)
      (m 9120 'sz-configuration-error)
      (m 9210 'sz-configuration-error)
      (m 9220 'sz-configuration-error)
      (m 9222 'sz-configuration-error)
      (m 9224 'sz-configuration-error)
      (m 9225 'sz-configuration-error)
      (m 9226 'sz-bad-input-error)
      (m 9227 'sz-error)
      (m 9228 'sz-configuration-error)
      (m 9229 'sz-error)
      (m 9240 'sz-configuration-error)
      (m 9241 'sz-configuration-error)
      (m 9250 'sz-configuration-error)
      (m 9251 'sz-configuration-error)
      (m 9252 'sz-configuration-error)
      (m 9253 'sz-configuration-error)
      (m 9254 'sz-configuration-error)
      (m 9255 'sz-configuration-error)
      (m 9256 'sz-configuration-error)
      (m 9257 'sz-configuration-error)
      (m 9258 'sz-configuration-error)
      (m 9259 'sz-configuration-error)
      (m 9260 'sz-configuration-error)
      (m 9261 'sz-configuration-error)
      (m 9264 'sz-configuration-error)
      (m 9265 'sz-configuration-error)
      (m 9266 'sz-configuration-error)
      (m 9267 'sz-error)
      (m 9268 'sz-error)
      (m 9269 'sz-configuration-error)
      (m 9270 'sz-configuration-error)
      (m 9271 'sz-error)
      (m 9272 'sz-error)
      (m 9273 'sz-error)
      (m 9274 'sz-error)
      (m 9275 'sz-error)
      (m 9276 'sz-error)
      (m 9277 'sz-error)
      (m 9278 'sz-error)
      (m 9279 'sz-error)
      (m 9280 'sz-error)
      (m 9281 'sz-error)
      (m 9282 'sz-error)
      (m 9283 'sz-error)
      (m 9284 'sz-configuration-error)
      (m 9285 'sz-configuration-error)
      (m 9286 'sz-configuration-error)
      (m 9287 'sz-error)
      (m 9288 'sz-error)
      (m 9289 'sz-error)
      (m 9290 'sz-error)
      (m 9292 'sz-configuration-error)
      (m 9293 'sz-configuration-error)
      (m 9295 'sz-configuration-error)
      (m 9296 'sz-configuration-error)
      (m 9297 'sz-configuration-error)
      (m 9298 'sz-configuration-error)
      (m 9299 'sz-error)
      (m 9300 'sz-configuration-error)
      (m 9301 'sz-configuration-error)
      (m 9305 'sz-error)
      (m 9308 'sz-configuration-error)
      (m 9309 'sz-configuration-error)
      (m 9310 'sz-configuration-error)
      (m 9311 'sz-error)
      (m 9406 'sz-error)
      (m 9408 'sz-configuration-error)
      (m 9409 'sz-configuration-error)
      (m 9410 'sz-error)
      (m 9411 'sz-error)
      (m 9413 'sz-configuration-error)
      (m 9414 'sz-bad-input-error)
      (m 9500 'sz-configuration-error)
      (m 9501 'sz-error)
      (m 9701 'sz-error)
      (m 9802 'sz-configuration-error)
      (m 9803 'sz-configuration-error)
      (m 9804 'sz-error)
      (m 9805 'sz-error)
      (m 9806 'sz-error))
    ht)
  "Hash table mapping Senzing error codes to condition class symbols.")

(defun lookup-exception-class (error-code)
  "Look up the condition class for an error code. Returns 'sz-error if not found."
  (gethash error-code *engine-exception-map* 'sz-error))
